### ISSUE TITLE
ruby-usdt should be installable on platforms that don't include DTrace

### ISSUE THREAD

**Issue by sax** [thekvn/ruby-usdt#10]
I don't know how complicated this would be, but it should be possible to include ruby-usdt in a project that will be installed on OSs that don't include DTrace.

For instance, if I'm writing code that will be deployed to an Illumos host, I may run tests in TravisCI, which will run in some Linux distro.

**Comment by sax** [comment]
Maybe the Ruby C extension can define dummy objects and methods if there is no DTrace? So there would still be hooks in Ruby, but they would be noop.

@kevinykchan I can play around with this, but wondered if you had any thoughts.

**Comment by chrisa** [comment]
In https://github.com/chrisa/node-dtrace-provider, I detect the lack of DTrace support and provide a stub no-op implementation in pure javascript. It's not perfect - it believes that all FreeBSD versions should have DTrace, and I'm not sure if it works on Windows - but something similar would be possible for Ruby.

**Comment by sax** [comment]
@chrisa I've only had a limited amount of time to play with this, but am moving forward very very slowly.

I was considering writing the stub implementation in C, in which case I was wondering if this would make a good addition to libusdt itself... if it can't find dtrace, maybe it can present a fake implementation to client libraries. In that case, wouldn't integration into other languages be much easier?

**Comment by sax** [comment]
@chrisa oh, if you'd take a pull request to libusdt, I'll work on that. Just trying to plan out the best approach before really diving into code.
